export const projectsData = [
  {
    id: 1,
    title: "Smart Watches E-Commerce Wevsite",
    category: "MERN Stack, E-Commerce",
    image: "https://i.ibb.co.com/sJsP1TyZ/Screenshot-2026-01-19-212039.png",
    desc: "This Twitch clone built with Next.js, Prisma, Tailwind, PostgreSQL, and TypeScript offers RTMP/WHIP streaming, real-time chat, and viewer count.",
    technologies: ["Next.js", "Node.js", "JavaScript", "Tailwind CSS", "MongoDB"],
    live: "https://smart-wrist-next-js-h1fl.vercel.app",
    github: "https://github.com/shiful33/smartWrist-next.js",
  },
  {
    id: 2,
    title: "Find Your Study Partners",
    category: "Full Stack",
    image: "https://i.ibb.co.com/B5vcphrJ/img13.png",
    desc: "Google Docs Clone is a full-stack app built with Next.js 15, Shadcn UI, and Tailwind CSS, offering real-time editing, collaboration, and comments.",
    technologies: ["Next.js", "Node.js", "JavaScript", "Tailwind CSS"],
    live: "https://study-partner-web-client-shiful33.netlify.app",
    github: "https://github.com/shiful33/care.io-next.js",
  },
  {
    id: 3,
    title: "Scholarship Management Find Scholarships For Stydy",
    category: "MERN Stack",
    image: "https://i.ibb.co.com/q3xdnP9G/img14.png",
    desc: "This Twitch clone built with Next.js, Prisma, Tailwind, PostgreSQL, and TypeScript offers RTMP/WHIP streaming, real-time chat, and viewer count.",
    technologies: ["React.js", "Node.js", "Express.js", "MongoDB", "Firebase"],
    live: "https://scholarship-management-c-5011a.firebaseapp.com",
    github: "https://github.com/shiful33/scholarship-management-platform-client",
  },
  {
    id: 4,
    title: "Zap Service, A Parcel Delivery Web App",
    category: "Full Stack",
    image: "https://i.ibb.co.com/R4d1V05F/Screenshot-2026-01-20-191321.png",
    desc: "Google Docs Clone is a full-stack app built with Next.js 15, Shadcn UI, and Tailwind CSS, offering real-time editing, collaboration, and comments.",
    technologies: ["Next.js", "Node.js", "JavaScript", "Tailwind CSS"],
    live: "https://zap-shift-client-lake.vercel.app/",
    github: "https://github.com/shiful33/zap-shift-client",
  },
  {
    id: 5,
    title: "Kidz Favorite Toys E-Commerce Website",
    category: "Frontend, E-Commerce",
    image: "https://i.ibb.co.com/XfjtfXFP/img7.png",
    desc: "A modern file storage platform built with Next.js, Shadcn UI, and TypeScript. It offers secure uploads, role-based permissions, and file organization.",
    technologies: ["React", "JavaScript", "MongoDB", "Tailwind", "Firebase"],
    live: "https://kids-toy-shop-shiful33.netlify.app/",
    github: "#",
  },

  {
    id: 6,
    title: "We Build Productive Apps Website",
    category: "Frontend",
    image: "https://i.ibb.co.com/9ks9xKyR/img8.png",
    desc: "This Twitch clone built with Next.js, Prisma, Tailwind, PostgreSQL, and TypeScript offers RTMP/WHIP streaming, real-time chat, and viewer count.",
    technologies: ["React.js", "Node.js", "Express.js", "MongoDB", "Firebase"],
    live: "https://hero-app-shiful33.netlify.app",
    github: "https://github.com/shiful33/hero-apps",
  },
  {
    id: 7,
    title: "Influencer products E-Commerce Website",
    category: "Frontend",
    image: "https://i.ibb.co.com/JRPLww29/img5.png",
    desc: "Google Docs Clone is a full-stack app built with Next.js 15, Shadcn UI, and Tailwind CSS, offering real-time editing, collaboration, and comments.",
    technologies: ["Next.js", "Node.js", "JavaScript", "Tailwind CSS"],
    live: "https://shiful33.github.io/influencer-gear",
    github: "https://github.com/shiful33/influencer-gear",
  },
  {
    id: 8,
    title: "Freshness You Can Count On, Prices You'll Love!",
    category: "Frontend",
    image: "https://i.ibb.co.com/sz8j31h/Screenshot-2026-01-20-175535.png",
    desc: "A modern file storage platform built with Next.js, Shadcn UI, and TypeScript. It offers secure uploads, role-based permissions, and file organization.",
    technologies: ["React", "JavaScript", "MongoDB", "Tailwind", "Firebase"],
    live: "https://naturels-platter-demo-website.netlify.app/",
    github: "https://github.com/shiful33/natures-platter-assaignment-2",
  },

  {
    id: 9,
    title: "Reliable Caregiving Services You Can Trust",
    category: "MERN Stack, Full Stack",
    image: "https://i.ibb.co.com/JRpZWg1q/Screenshot-2026-02-05-063220.png",
    desc: "This Twitch clone built with Next.js, Prisma, Tailwind, PostgreSQL, and TypeScript offers RTMP/WHIP streaming, real-time chat, and viewer count.",
    technologies: ["Next.js", "Node.js", "JavaScript", "Tailwind CSS", "Vercel"],
    live: "https://care-io-next-js.vercel.app",
    github: "https://app.netlify.com/projects/graceful-sprite-e76c6b/overview",
  },
  {
    id: 10,
    title: "Deal your Products in a Smart way!",
    category: "Full Stack, E-Commerce",
    image: "https://i.ibb.co.com/yc0q9Yqm/Screenshot-2026-01-20-181052.png",
    desc: "Google Docs Clone is a full-stack app built with Next.js 15, Shadcn UI, and Tailwind CSS, offering real-time editing, collaboration, and comments.",
    technologies: ["React.js", "Node.js", "JavaScript", "Tailwind CSS"],
    live: "https://smart-deals-web-app-shiful33.netlify.app",
    github: "https://github.com/shiful33/smart-deals-client",
  },
  {
    id: 11,
    title: "It's good tea time at The Tea House",
    category: "Frontend, E-Commerce",
    image: "https://i.ibb.co.com/XrmWGQsZ/img2.png",
    desc: "A modern file storage platform built with Next.js, Shadcn UI, and TypeScript. It offers secure uploads, role-based permissions, and file organization.",
    technologies: ["React", "JavaScript", "MongoDB", "Tailwind", "Firebase"],
    live: "https://shiful33.github.io/tea-house-projects-with-tailwind",
    github: "https://github.com/shiful33/tea-house-projects-with-tailwind",
  },

  {
    id: 12,
    title: "Plant a Tree, Grow a Future Website",
    category: "MERN Stack, E-Commerce",
    image: "https://i.ibb.co.com/ccVwHykz/img15.png",
    desc: "This Twitch clone built with Next.js, Prisma, Tailwind, PostgreSQL, and TypeScript offers RTMP/WHIP streaming, real-time chat, and viewer count.",
    technologies: ["React.js", "Node.js", "Express.js", "MongoDB", "Firebase"],
    live: "https://green-earth-assignment-6-shiful33.netlify.app",
    github: "https://github.com/shiful33/Green-Earth-assignment-6",
  },
  {
    id: 13,
    title: "Book Shop E-Commerce Website",
    category: "Frontend, E-Commerce",
    image: "https://i.ibb.co.com/HpXS0dR7/Screenshot-2026-01-20-182526.png",
    desc: "Google Docs Clone is a full-stack app built with Next.js 15, Shadcn UI, and Tailwind CSS, offering real-time editing, collaboration, and comments.",
    technologies: ["JavaScript", "Tailwind CSS", "HTML5"],
    live: "https://book-shop-web-app-shiful33.netlify.app",
    github: "#",
  },
  {
    id: 14,
    title: "Beauty Care E-Commerce Website",
    category: "Frontend, E-Commerce",
    image: "https://i.ibb.co.com/j94kW24m/img1.png",
    desc: "A modern file storage platform built with Next.js, Shadcn UI, and TypeScript. It offers secure uploads, role-based permissions, and file organization.",
    technologies: ["Tailwind", "JavaScript", "MongoDB",],
    live: "https://shiful33.github.io/beautycare-e-commerce-website",
    github: "https://github.com/shiful33/beautycare-e-commerce-website",
  },
  {
    id: 15,
    title: "ENGLISH  JANALA Web App",
    category: "Frontend",
    image: "https://i.ibb.co.com/bjkh4j8x/img3.png",
    desc: "A modern file storage platform built with Next.js, Shadcn UI, and TypeScript. It offers secure uploads, role-based permissions, and file organization.",
    technologies: ["React", "JavaScript", "MongoDB", "Tailwind", "Firebase"],
    live: "https://shiful33.github.io/english-janala-web-App",
    github: "https://github.com/shiful33/english-janala-web-App",
  },
  {
    id: 16,
    title: "Flowers Shop E-Commerce Web Design",
    category: "Frontend, E-Commerce",
    image: "https://i.ibb.co.com/rRK4qfY0/img4.png",
    desc: "A modern file storage platform built with Next.js, Shadcn UI, and TypeScript. It offers secure uploads, role-based permissions, and file organization.",
    technologies: ["JavaScript", "Tailwind", "HTML5"],
    live: "https://shiful33.github.io/B12A02-Responsive-Flowers-aasignment2",
    github: "https://github.com/shiful33/B12A02-Responsive-Flowers-aasignment2",
  },
  {
    id: 17,
    title: "Emergency Service Directory Web Application",
    category: "Frontend",
    image: "https://i.ibb.co.com/Txb5mfkL/Screenshot-2026-01-20-224332.png",
    desc: "A modern file storage platform built with Next.js, Shadcn UI, and TypeScript. It offers secure uploads, role-based permissions, and file organization.",
    technologies: ["React.js", "JavaScript", "MongoDB", "Tailwind", "Firebase"],
    live: "https://demo-emergency-hotline-shiful33.netlify.app",
    github: "http://github.com/shiful33/Emergency-Hotline-B12-A5",
  },
  {
    id: 18,
    title: "A Simple Landing Page Design",
    category: "Frontend",
    image: "https://i.ibb.co.com/RpDFzyqb/img12.png",
    desc: "A modern file storage platform built with Next.js, Shadcn UI, and TypeScript. It offers secure uploads, role-based permissions, and file organization.",
    technologies: ["React", "JavaScript", "MongoDB", "Tailwind", "Firebase"],
    live: "https://nimble-choux-246e0e.netlify.app",
    github: "#",
  }
];