export const projectsData = [
  {
    id: 1,
    title: "GameHub: The Ultimate Livestreaming Platform",
    category: "MERN Stack",
    image: "https://i.ibb.co.com/q3xdnP9G/img14.png",
    desc: "This Twitch clone built with Next.js, Prisma, Tailwind, PostgreSQL, and TypeScript offers RTMP/WHIP streaming, real-time chat, and viewer count.",
    technologies: ["React.js", "Node.js", "Express.js", "MongoDB", "Firebase"],
    live: "https://scholarship-management-c-5011a.firebaseapp.com",
    github: "https://github.com/shiful33/scholarship-management-platform-client",
  },
  {
    id: 2,
    title: "Google Docs 2.0: Next-Gen Real-Time Collaboration",
    category: "Full Stack",
    image: "https://i.ibb.co.com/B5vcphrJ/img13.png",
    desc: "Google Docs Clone is a full-stack app built with Next.js 15, Shadcn UI, and Tailwind CSS, offering real-time editing, collaboration, and comments.",
    technologies: ["Next.js", "Node.js", "JavaScript", "Tailwind CSS"],
    live: "https://study-partner-web-client-shiful-33.netlify.app",
    github: "https://github.com/shiful33/study-partner-web-client",
  },
  {
    id: 3,
    title: "Google Drive Clone: The Ultimate File Sharing Platform",
    category: "Frontend",
    image: "https://i.ibb.co.com/XfjtfXFP/img7.png",
    desc: "A modern file storage platform built with Next.js, Shadcn UI, and TypeScript. It offers secure uploads, role-based permissions, and file organization.",
    technologies: ["React", "JavaScript", "MongoDB", "Tailwind", "Firebase"],
    live: "https://kids-toy-shop-shiful33.netlify.app/",
    github: "#",
  },

  {
    id: 4,
    title: "GameHub: The Ultimate Livestreaming Platform",
    category: "MERN Stack",
    image: "https://i.ibb.co.com/9ks9xKyR/img8.png",
    desc: "This Twitch clone built with Next.js, Prisma, Tailwind, PostgreSQL, and TypeScript offers RTMP/WHIP streaming, real-time chat, and viewer count.",
    technologies: ["React.js", "Node.js", "Express.js", "MongoDB", "Firebase"],
    live: "https://hero-app-shiful33.netlify.app",
    github: "https://github.com/shiful33/hero-apps",
  },
  {
    id: 5,
    title: "Google Docs 2.0: Next-Gen Real-Time Collaboration",
    category: "Frontend",
    image: "https://i.ibb.co.com/B5vcphrJ/img13.png",
    desc: "Google Docs Clone is a full-stack app built with Next.js 15, Shadcn UI, and Tailwind CSS, offering real-time editing, collaboration, and comments.",
    technologies: ["Next.js", "Node.js", "JavaScript", "Tailwind CSS"],
    live: "https://nimble-choux-246e0e.netlify.app",
    github: "https://app.netlify.com/projects/nimble-choux-246e0e/overview",
  },
  {
    id: 6,
    title: "Google Drive Clone: The Ultimate File Sharing Platform",
    category: "Frontend",
    image: "https://i.ibb.co.com/XfjtfXFP/img7.png",
    desc: "A modern file storage platform built with Next.js, Shadcn UI, and TypeScript. It offers secure uploads, role-based permissions, and file organization.",
    technologies: ["React", "JavaScript", "MongoDB", "Tailwind", "Firebase"],
    live: "https://naturels-platter-demo-website.netlify.app",
    github: "https://github.com/shiful33/natures-platter-assaignment-2",
  },

  {
    id: 7,
    title: "GameHub: The Ultimate Livestreaming Platform",
    category: "MERN Stack",
    image: "https://i.ibb.co.com/tpgMQwWX/img9.png",
    desc: "This Twitch clone built with Next.js, Prisma, Tailwind, PostgreSQL, and TypeScript offers RTMP/WHIP streaming, real-time chat, and viewer count.",
    technologies: ["React.js", "Node.js", "Express.js", "MongoDB", "Firebase"],
    live: "https://graceful-sprite-e76c6b.netlify.app",
    github: "https://app.netlify.com/projects/graceful-sprite-e76c6b/overview",
  },
  {
    id: 8,
    title: "Google Docs 2.0: Next-Gen Real-Time Collaboration",
    category: "Full Stack",
    image: "https://i.ibb.co.com/Mxtkrrb0/img11.png",
    desc: "Google Docs Clone is a full-stack app built with Next.js 15, Shadcn UI, and Tailwind CSS, offering real-time editing, collaboration, and comments.",
    technologies: ["Next.js", "Node.js", "JavaScript", "Tailwind CSS"],
    live: "https://naturels-platter-demo-website.netlify.app",
    github: "https://app.netlify.com/projects/naturels-platter-demo-website/overview",
  },
  {
    id: 9,
    title: "Google Drive Clone: The Ultimate File Sharing Platform",
    category: "Frontend",
    image: "https://i.ibb.co.com/KcyP5j62/img10.png",
    desc: "A modern file storage platform built with Next.js, Shadcn UI, and TypeScript. It offers secure uploads, role-based permissions, and file organization.",
    technologies: ["React", "JavaScript", "MongoDB", "Tailwind", "Firebase"],
    live: "https://tailwind-e-commerce-project.netlify.app",
    github: "https://app.netlify.com/projects/tailwind-e-commerce-project/overview",
  },

  {
    id: 10,
    title: "GameHub: The Ultimate Livestreaming Platform",
    category: "MERN Stack",
    image: "https://i.ibb.co.com/ccVwHykz/img15.png",
    desc: "This Twitch clone built with Next.js, Prisma, Tailwind, PostgreSQL, and TypeScript offers RTMP/WHIP streaming, real-time chat, and viewer count.",
    technologies: ["React.js", "Node.js", "Express.js", "MongoDB", "Firebase"],
    live: "https://green-earth-assignment-6-shiful33.netlify.app",
    github: "https://app.netlify.com/projects/green-earth-assignment-6-shiful33/overview",
  },
  {
    id: 11,
    title: "Google Docs 2.0: Next-Gen Real-Time Collaboration",
    category: "Frontend",
    image: "https://i.ibb.co.com/XrmWGQsZ/img2.png",
    desc: "Google Docs Clone is a full-stack app built with Next.js 15, Shadcn UI, and Tailwind CSS, offering real-time editing, collaboration, and comments.",
    technologies: ["Next.js", "Node.js", "JavaScript", "Tailwind CSS"],
    live: "https://shiful33.github.io/tea-house-projects-with-tailwind",
    github: "https://github.com/shiful33/tea-house-projects-with-tailwind",
  },
  {
    id: 12,
    title: "Google Drive Clone: The Ultimate File Sharing Platform",
    category: "Frontend",
    image: "https://i.ibb.co.com/j94kW24m/img1.png",
    desc: "A modern file storage platform built with Next.js, Shadcn UI, and TypeScript. It offers secure uploads, role-based permissions, and file organization.",
    technologies: ["React", "JavaScript", "MongoDB", "Tailwind", "Firebase"],
    live: "https://shiful33.github.io/beautycare-e-commerce-website",
    github: "https://github.com/shiful33/beautycare-e-commerce-website",
  },
  {
    id: 13,
    title: "Google Drive Clone: The Ultimate File Sharing Platform",
    category: "Frontend",
    image: "https://i.ibb.co.com/bjkh4j8x/img3.png",
    desc: "A modern file storage platform built with Next.js, Shadcn UI, and TypeScript. It offers secure uploads, role-based permissions, and file organization.",
    technologies: ["React", "JavaScript", "MongoDB", "Tailwind", "Firebase"],
    live: "https://shiful33.github.io/english-janala-web-App",
    github: "https://github.com/shiful33/english-janala-web-App",
  },
  {
    id: 14,
    title: "Google Drive Clone: The Ultimate File Sharing Platform",
    category: "Frontend",
    image: "https://i.ibb.co.com/rRK4qfY0/img4.png",
    desc: "A modern file storage platform built with Next.js, Shadcn UI, and TypeScript. It offers secure uploads, role-based permissions, and file organization.",
    technologies: ["React", "JavaScript", "MongoDB", "Tailwind", "Firebase"],
    live: "https://shiful33.github.io/english-janala-web-App",
    github: "https://github.com/shiful33/english-janala-web-App",
  }
];